# Generated by Django 5.1.1 on 2025-02-10 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mise', models.FloatField(default=0, max_length=6)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('cote_totale', models.FloatField(default=1, max_length=5)),
                ('paris_id', models.JSONField(default=list, verbose_name='IDs des paris')),
                ('paris_cotes', models.JSONField(default=dict, verbose_name='Cotes des paris')),
                ('actif', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Bets',
                'verbose_name_plural': 'Bets',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sport', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('equipe1', models.CharField(max_length=200)),
                ('equipe2', models.CharField(max_length=200)),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('niveau', models.CharField(max_length=50)),
                ('poule', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'creation_bdd_match',
                'unique_together': {('sport', 'date', 'heure', 'equipe1', 'equipe2')},
            },
        ),
        migrations.CreateModel(
            name='Cote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coteN', models.FloatField(default=1.1, max_length=5)),
                ('cote1', models.FloatField(default=1.1, max_length=5)),
                ('cote2', models.FloatField(default=1.1, max_length=5)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotes', to='listings.match')),
            ],
        ),
        migrations.CreateModel(
            name='Pari',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('selection', models.CharField(choices=[('1', 'Victoire Équipe 1'), ('N', 'Match Nul'), ('2', 'Victoire Équipe 2')], max_length=1, verbose_name='Pronostic')),
                ('cote', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cote')),
                ('actif', models.BooleanField(default=True, verbose_name='Pari actif')),
                ('resultat', models.CharField(choices=[('NaN', 'En attente'), ('1', 'Victoire Équipe 1'), ('N', 'Match Nul'), ('2', 'Victoire Équipe 2')], default='NaN', max_length=3, verbose_name='Résultat du pari')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('bet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paris', to='listings.bet', verbose_name='Bet')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paris', to='listings.match', verbose_name='Match')),
            ],
            options={
                'verbose_name': 'Pari',
                'verbose_name_plural': 'Paris',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('EARN', 'Points gagnés'), ('SPEND', 'Points dépensés')], max_length=5)),
                ('reason', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
