# Generated by Django 5.1.1 on 2025-02-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pari',
            name='groupe',
        ),
    ]
