# Generated by Django 5.1.2 on 2025-02-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='forfait_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='forfait_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='match_joue',
            field=models.BooleanField(default=False),
        ),
    ]
