# Generated by Django 5.1.2 on 2025-01-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('sport', 'date', 'heure', 'equipe1', 'equipe2')},
        ),
    ]
