# Generated by Django 5.1.1 on 2024-10-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('niveau', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('equipe1', models.CharField(max_length=100)),
                ('equipe2', models.CharField(max_length=100)),
                ('passe', models.BooleanField()),
            ],
        ),
    ]
