# Generated by Django 5.1.1 on 2025-02-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='paris_ids',
            new_name='paris_id',
        ),
    ]
