# Generated by Django 5.1.2 on 2025-02-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_match_forfait_1_match_forfait_2_match_match_joue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academie', models.CharField(max_length=100)),
                ('poule', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='arbitre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='commentaires',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='lieu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
