# Generated by Django 5.1.2 on 2025-01-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_match_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='equipe1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='match',
            name='equipe2',
            field=models.CharField(max_length=200),
        ),
    ]
