# Generated by Django 5.1.1 on 2025-02-05 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_pari_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupePari',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mise', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mise totale')),
                ('cote_totale', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cote totale')),
                ('gain_potentiel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gain potentiel')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('GAGNE', 'Gagné'), ('PERDU', 'Perdu'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=10, verbose_name='Statut du groupe')),
                ('type_pari', models.CharField(choices=[('SIMPLE', 'Pari simple'), ('COMBINE', 'Pari combiné')], default='SIMPLE', max_length=7, verbose_name='Type de pari')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Groupe de paris',
                'verbose_name_plural': 'Groupes de paris',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='pari',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paris', to='listings.groupepari', verbose_name='Groupe de paris'),
        ),
        migrations.DeleteModel(
            name='PariGroupe',
        ),
    ]
