# Generated by Django 5.1.1 on 2024-10-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_equipes_matchs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.AlterField(
            model_name='equipes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchs',
            name='equipe1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipe1', to='listings.equipes'),
        ),
        migrations.AlterField(
            model_name='matchs',
            name='equipe2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipe2', to='listings.equipes'),
        ),
    ]
