# Generated by Django 5.1.2 on 2025-02-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_ecole_equipe_match_arbitre_match_commentaires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='academie',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
