# Generated by Django 5.1.1 on 2025-01-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_match_equipe1_alter_match_equipe2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cote',
            name='type_cote',
        ),
        migrations.RemoveField(
            model_name='cote',
            name='valeur',
        ),
        migrations.AddField(
            model_name='cote',
            name='cote1',
            field=models.FloatField(default=1.1, max_length=5),
        ),
        migrations.AddField(
            model_name='cote',
            name='cote2',
            field=models.FloatField(default=1.1, max_length=5),
        ),
        migrations.AddField(
            model_name='cote',
            name='coteN',
            field=models.FloatField(default=1.1, max_length=5),
        ),
    ]
