# Generated by Django 5.1.2 on 2024-12-02 15:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_delete_band_alter_equipes_id_alter_matchs_equipe1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cote', models.CharField(max_length=50)),
                ('valeur', models.FloatField(validators=[django.core.validators.MinValueValidator(1.01)])),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sport', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('equipe1', models.CharField(max_length=100)),
                ('equipe2', models.CharField(max_length=100)),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('niveau', models.CharField(max_length=50)),
                ('poule', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'creation_bdd_match',
            },
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='equipe1',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='equipe2',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='cote',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotes', to='listings.match'),
        ),
        migrations.DeleteModel(
            name='Equipes',
        ),
        migrations.DeleteModel(
            name='Matchs',
        ),
    ]
