# Generated by Django 5.1.1 on 2025-02-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_groupepari_pari_groupe_delete_parigroupe'),
    ]

    operations = [
    ]
