# Generated by Django 5.1.1 on 2025-01-11 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_cote_type_cote_remove_cote_valeur_cote_cote1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('1', 'Victoire Équipe 1'), ('N', 'Match Nul'), ('2', 'Victoire Équipe 2')], max_length=1, verbose_name='Pronostic')),
                ('actif', models.BooleanField(default=True, verbose_name='Pari actif')),
                ('resultat', models.CharField(choices=[('NaN', 'En attente'), ('1', 'Victoire Équipe 1'), ('N', 'Match Nul'), ('2', 'Victoire Équipe 2')], default='NaN', max_length=3, verbose_name='Résultat du pari')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paris', to='listings.match', verbose_name='Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pari',
                'verbose_name_plural': 'Paris',
                'ordering': ['-date_creation'],
            },
        ),
    ]
