# Generated by Django 5.1.1 on 2025-02-20 13:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_match_academie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pari',
            name='resultat',
            field=models.CharField(choices=[('NaN', 'En attente'), ('1', 'Victoire Équipe 1'), ('N', 'Match Nul'), ('2', 'Victoire Équipe 2'), ('F1', 'Forfait Équipe 1'), ('F2', 'Forfait Équipe 2')], default='NaN', max_length=3, verbose_name='Résultat du pari'),
        ),
        migrations.CreateModel(
            name='UserLoginTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_login_count', models.IntegerField(default=0)),
                ('last_reset', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
