# Generated by Django 5.1.1 on 2025-02-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_userpoints_user'),
        ('listings', '0005_pari'),
    ]

    operations = [
    ]
