# Generated by Django 5.1.1 on 2025-02-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_pari_resultat_userlogintracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='annule',
            field=models.BooleanField(default='False'),
        ),
    ]
