# Generated by Django 5.1.1 on 2025-02-25 16:02

import django.db.models.deletion
import listings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_bet_annule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='photo_profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=listings.models.user_directory_path)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('texte', models.TextField(verbose_name='Description du match')),
                ('sport', models.CharField(max_length=100, verbose_name='Sport')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='press_photos/', verbose_name='Photo du match')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('url_externe', models.URLField(blank=True, null=True, verbose_name='URL externe')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.match', verbose_name='Match associé')),
            ],
            options={
                'verbose_name': 'Article de presse',
                'verbose_name_plural': 'Articles de presse',
                'ordering': ['-date_creation'],
            },
        ),
    ]
