# Generated by Django 5.1.1 on 2024-12-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_pointtransaction_userpoints_delete_userpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
    ]
