# Generated by Django 5.1.1 on 2025-02-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_userpoints_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pari',
            name='cote',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='pari',
            name='mise',
            field=models.IntegerField(default=0),
        ),
    ]
