# Generated by Django 5.1.2 on 2025-06-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_emailverificationtoken_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('poule', models.CharField(max_length=10)),
                ('equipe', models.CharField(max_length=100)),
                ('place', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('joues', models.IntegerField(default=0)),
                ('penalites', models.IntegerField(default=0)),
                ('gagnes', models.IntegerField(default=0)),
                ('nuls', models.IntegerField(default=0)),
                ('perdus', models.IntegerField(default=0)),
                ('gagnes_forfait', models.IntegerField(default=0)),
                ('perdus_forfait', models.IntegerField(default=0)),
                ('gagnes_tv', models.IntegerField(default=0)),
                ('perdus_tv', models.IntegerField(default=0)),
                ('buts_avantage', models.IntegerField(default=0)),
                ('buts_desavantage', models.IntegerField(default=0)),
                ('pour', models.IntegerField(default=0)),
                ('contre', models.IntegerField(default=0)),
                ('difference', models.IntegerField(default=0)),
                ('academie', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sport', 'niveau', 'poule', 'place'],
                'unique_together': {('sport', 'niveau', 'poule', 'equipe', 'academie')},
            },
        ),
    ]
