"""
Django settings for merchex project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-41w*dyx86+2cb*lms16sg_8m0-z3=rn-3_#wsxf%b0mj_v_z+v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['213.32.91.54','vps-dde127df.vps.ovh.net','localhost','127.0.0.1','campus-league.com','www.campus-league.com','test.campus-league.com']

# Paramètres pour fonctionner derrière un proxy
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Paramètres de sécurité recommandés ces paramètres servent à forcer le passage en HTTPS --> pas possible si test en local
SESSION_COOKIE_SECURE = True #temporairement à False pour tester mais remettre à True avant de sortir l'appli !!!!!!!!!
CSRF_COOKIE_SECURE = True #temporairement à False pour tester mais remettre à True avant de sortir l'appli
SECURE_SSL_REDIRECT = True #temporairement à False pour tester mais remettre à True avant de sortir l'appli

# Application definition

INSTALLED_APPS = [
    'daphne',  # ← IMPORTANT: Doit être en premier pour WebSocket
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'listings',
    'rest_framework',
    'background_task',
    'creation_bdd',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_crontab',
    'django_extensions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  
]

CORS_ALLOW_CREDENTIALS = True

#SESSION_COOKIE_SAMESITE = 'None'  # Permet les requêtes cross-origin

SECURE_HSTS_SECONDS = 31536000  # 1 an
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Si vous permettez un accès sans restriction
    ],
}

AUTH_USER_MODEL = 'auth.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

CORS_ALLOW_ALL_ORIGINS = True

# CORS_ALLOWED_ORIGINS = [
#     "https://campus-league.com",
#     "https://www.campus-league.com",
#     "http://campus-league.com",
#     "http://www.campus-league.com",
# ]

FRONTEND_URL = 'https://campus-league.com/'

SIMPLE_JWT = {
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),  # Token de connexion valide 7 jours
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),  # Token de renouvellement valide 30 jours
    'ROTATE_REFRESH_TOKENS': True,  # Génère un nouveau refresh token à chaque renouvellement
    # Note: BLACKLIST_AFTER_ROTATION nécessite 'rest_framework_simplejwt.token_blacklist' dans INSTALLED_APPS
}

CRONJOBS = [
    # Mise à jour des cotes - tous les jours à minuit
    ('0 0 * * *', 'cron.update_all_cotes'),

    # Réinitialisation des compteurs de connexion - tous les jours à minuit
    ('0 0 * * *', 'cron.reset_login_counters'),

    # Actualisation des données de matchs depuis le site FFSU - toutes les 30 minutes
    ('*/30 * * * *', 'cron.update_matches_data'),

    # Actualisation des classements - toutes les 30 minutes
    ('*/30 * * * *', 'cron.update_classements_data'),
]

ROOT_URLCONF = 'merchex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'merchex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/home/ubuntu/BDD/merchex/logs/django.log', 
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'ssl0.ovh.net'  # ex: smtp.gmail.com
EMAIL_PORT = 587  # Port standard pour TLS
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'alexandre.montariol@campus-league.com'
EMAIL_HOST_PASSWORD = 'Patricia12_!'  # Utilisez des variables d'environnement en production
DEFAULT_FROM_EMAIL = 'alexandre.montariol@campus-league.com'

# Pour le développement, vous pouvez utiliser l'option de console pour voir les emails dans la console:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Paramètres de l'application
EMAIL_VERIFICATION_EXPIRY_DAYS = 2  # Délai d'expiration du token de vérification


# ================== WebSocket Configuration (Django Channels) ==================

# ASGI Application
ASGI_APPLICATION = 'merchex.asgi.application'

# Configuration du Channel Layer (Redis pour production)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
            "capacity": 1500,  # Nombre max de messages dans un channel
            "expiry": 10,  # TTL des messages en secondes
        },
    },
}

# Pour le développement sans Redis, utiliser InMemoryChannelLayer :
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer'
#     }
# }
