"""
Django settings for merchex project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-41w*dyx86+2cb*lms16sg_8m0-z3=rn-3_#wsxf%b0mj_v_z+v'

<<<<<<< Updated upstream
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
=======
# Détection automatique de l'environnement
IS_PRODUCTION = os.path.exists('/home/ubuntu')  # Détecte si on est sur le serveur Linux
IS_LOCAL = sys.platform == 'win32'  # Détecte si on est sur Windows
>>>>>>> Stashed changes


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION

# Hosts autorisés selon l'environnement
if IS_PRODUCTION:
    ALLOWED_HOSTS = ['213.32.91.54', 'vps-dde127df.vps.ovh.net', 'campus-league.com', 'www.campus-league.com']
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Paramètres pour fonctionner derrière un proxy
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

<<<<<<< Updated upstream
# Paramètres de sécurité recommandés ces paramètres servent à forcer le passage en HTTPS --> pas possible si test en local
SESSION_COOKIE_SECURE = True #temporairement à False pour tester mais remettre à True avant de sortir l'appli !!!!!!!!!
CSRF_COOKIE_SECURE = True #temporairement à False pour tester mais remettre à True avant de sortir l'appli
SECURE_SSL_REDIRECT = True #temporairement à False pour tester mais remettre à True avant de sortir l'appli

=======
# Paramètres de sécurité selon l'environnement
if IS_PRODUCTION:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
>>>>>>> Stashed changes
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'listings',
    'rest_framework',
    'background_task', 
    'creation_bdd',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_crontab',
    'django_extensions',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'listings.middleware.AutoTokenRenewalMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  
]

CORS_ALLOW_CREDENTIALS = True

#SESSION_COOKIE_SAMESITE = 'None'  # Permet les requêtes cross-origin

SECURE_HSTS_SECONDS = 31536000  # 1 an
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Si vous permettez un accès sans restriction
    ],
}

AUTH_USER_MODEL = 'auth.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# CORS selon l'environnement
if IS_PRODUCTION:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        "https://campus-league.com",
        "https://www.campus-league.com",
        "http://campus-league.com",
        "http://www.campus-league.com",
    ]
else:
    CORS_ALLOW_ALL_ORIGINS = True 

# CORS_ALLOWED_ORIGINS = [
#     "https://campus-league.com",
#     "https://www.campus-league.com",
#     "http://campus-league.com",
#     "http://www.campus-league.com",
# ]

FRONTEND_URL = 'https://campus-league.com/'

SIMPLE_JWT = {
    'USER_ID_FIELD': 'id', 
    'USER_ID_CLAIM': 'user_id',
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),  # ← Changer de 1 à 30 jours
    'REFRESH_TOKEN_LIFETIME': timedelta(days=60),  # Ajout refresh token
    'ROTATE_REFRESH_TOKENS': True,  # Rotation des refresh tokens
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist les anciens tokens
}

CRONJOBS = [
    ('0 0 * * *', 'listings.cron.update_all_cotes'),
    ('0 0 * * *', 'django.core.management.call_command', ['reset_login_counts']),
    ('*/30 * * * *', 'django.core.management.call_command', ['update_matches']),  # Toutes les 30 min
    ('*/30 * * * *', 'django.core.management.call_command', ['update_classements']), # Toutes les 30 min
]

ROOT_URLCONF = 'merchex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'merchex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Base de données selon l'environnement
if IS_PRODUCTION:
    # PRODUCTION : Garder votre configuration SQLite existante qui fonctionne
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',  # Votre DB de production actuelle
        }
    }
else:
    # LOCAL : Base de données séparée pour les tests en développement
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db_local_test.sqlite3',  # DB séparée pour éviter les conflits
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configuration des logs selon l'environnement
if IS_PRODUCTION:
    # Configuration logs production
    LOGS_DIR = Path('/home/ubuntu/BDD/merchex/logs')
    LOGS_DIR.mkdir(exist_ok=True)
    
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'file': {
                'level': 'INFO',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': LOGS_DIR / 'django.log',
                'maxBytes': 1024*1024*5,
                'backupCount': 5,
            },
            'console': {
                'level': 'ERROR',  # Moins verbeux en production
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file', 'console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }
else:
    # Configuration logs locale (plus simple)
    LOGS_DIR = BASE_DIR / 'logs'
    LOGS_DIR.mkdir(exist_ok=True)
    
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'level': 'DEBUG',
                'class': 'logging.StreamHandler',
            },
            'file': {
                'level': 'DEBUG',
                'class': 'logging.FileHandler',
                'filename': LOGS_DIR / 'django_local.log',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console', 'file'],
                'level': 'DEBUG',
                'propagate': False,
            },
        },
    }


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'ssl0.ovh.net'  # ex: smtp.gmail.com
EMAIL_PORT = 587  # Port standard pour TLS
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'alexandre.montariol@campus-league.com'
EMAIL_HOST_PASSWORD = 'Patricia12_!'  # Utilisez des variables d'environnement en production
DEFAULT_FROM_EMAIL = 'alexandre.montariol@campus-league.com'

# Pour le développement, vous pouvez utiliser l'option de console pour voir les emails dans la console:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Paramètres de l'application
EMAIL_VERIFICATION_EXPIRY_DAYS = 2  # Délai d'expiration du token de vérification

